// <auto-generated />
using System;
using Cinema.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinema.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729150000_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinema.Api.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A história do físico J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica.",
                            DurationMinutes = 180,
                            Genre = "Drama/Biografia",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7z0I4E2K.jpg",
                            Title = "Oppenheimer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Paul Atreides se une aos Fremen em uma jornada de vingança contra os conspiradores que destruíram sua família.",
                            DurationMinutes = 166,
                            Genre = "Ficção Científica",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/8b8R8l1QmXLXQm3Fk0M3nL8M7yT.jpg",
                            Title = "Duna: Parte 2"
                        });
                });

            modelBuilder.Entity("Cinema.Api.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ReservedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Cinema.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Columns")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Columns = 4,
                            Name = "Sala 1",
                            Rows = 5
                        });
                });

            modelBuilder.Entity("Cinema.Api.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Row", "Number")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1,
                            RoomId = 1,
                            Row = "A"
                        },
                        new
                        {
                            Id = 2,
                            Number = 2,
                            RoomId = 1,
                            Row = "A"
                        },
                        new
                        {
                            Id = 3,
                            Number = 3,
                            RoomId = 1,
                            Row = "A"
                        },
                        new
                        {
                            Id = 4,
                            Number = 4,
                            RoomId = 1,
                            Row = "A"
                        },
                        new
                        {
                            Id = 5,
                            Number = 1,
                            RoomId = 1,
                            Row = "B"
                        },
                        new
                        {
                            Id = 6,
                            Number = 2,
                            RoomId = 1,
                            Row = "B"
                        },
                        new
                        {
                            Id = 7,
                            Number = 3,
                            RoomId = 1,
                            Row = "B"
                        },
                        new
                        {
                            Id = 8,
                            Number = 4,
                            RoomId = 1,
                            Row = "B"
                        },
                        new
                        {
                            Id = 9,
                            Number = 1,
                            RoomId = 1,
                            Row = "C"
                        },
                        new
                        {
                            Id = 10,
                            Number = 2,
                            RoomId = 1,
                            Row = "C"
                        },
                        new
                        {
                            Id = 11,
                            Number = 3,
                            RoomId = 1,
                            Row = "C"
                        },
                        new
                        {
                            Id = 12,
                            Number = 4,
                            RoomId = 1,
                            Row = "C"
                        },
                        new
                        {
                            Id = 13,
                            Number = 1,
                            RoomId = 1,
                            Row = "D"
                        },
                        new
                        {
                            Id = 14,
                            Number = 2,
                            RoomId = 1,
                            Row = "D"
                        },
                        new
                        {
                            Id = 15,
                            Number = 3,
                            RoomId = 1,
                            Row = "D"
                        },
                        new
                        {
                            Id = 16,
                            Number = 4,
                            RoomId = 1,
                            Row = "D"
                        },
                        new
                        {
                            Id = 17,
                            Number = 1,
                            RoomId = 1,
                            Row = "E"
                        },
                        new
                        {
                            Id = 18,
                            Number = 2,
                            RoomId = 1,
                            Row = "E"
                        },
                        new
                        {
                            Id = 19,
                            Number = 3,
                            RoomId = 1,
                            Row = "E"
                        },
                        new
                        {
                            Id = 20,
                            Number = 4,
                            RoomId = 1,
                            Row = "E"
                        });
                });

            modelBuilder.Entity("Cinema.Api.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2026, 8, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 1,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 8, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 35.00m
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2026, 8, 1, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 1,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 8, 1, 19, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 40.00m
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2026, 8, 1, 17, 46, 0, 0, DateTimeKind.Utc),
                            MovieId = 2,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 8, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 35.00m
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new DateTime(2026, 8, 1, 22, 46, 0, 0, DateTimeKind.Utc),
                            MovieId = 2,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 8, 1, 20, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 40.00m
                        });
                });

            modelBuilder.Entity("Cinema.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatId");

                    b.HasIndex("SessionId", "SeatId")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Cinema.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@cinema.com",
                            Name = "Administrador",
                            PasswordHash = "8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@email.com",
                            Name = "Usuário Teste",
                            PasswordHash = "04F8996DA763B7A969B1028EE3007569EAF3A635486DDAB211D512C85B9DF8FB",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("Cinema.Api.Models.Reservation", b =>
                {
                    b.HasOne("Cinema.Api.Models.Session", "Session")
                        .WithMany("Reservations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Cinema.Api.Models.Seat", b =>
                {
                    b.HasOne("Cinema.Api.Models.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Cinema.Api.Models.Session", b =>
                {
                    b.HasOne("Cinema.Api.Models.Movie", "Movie")
                        .WithMany("Sessions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Api.Models.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Cinema.Api.Models.Ticket", b =>
                {
                    b.HasOne("Cinema.Api.Models.Reservation", "Reservation")
                        .WithMany("Tickets")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Api.Models.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Api.Models.Session", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Seat");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Cinema.Api.Models.Movie", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Cinema.Api.Models.Reservation", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cinema.Api.Models.Room", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Cinema.Api.Models.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cinema.Api.Models.Session", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
